backend:
  # test cms layout locally
  # name: test-repo
  # use cms layout from github
  name: git-gateway
  branch: main

# publish_mode: editorial_workflow
# site_url: https://frasersgh.com/
# display_url: Frasers Website
logo_url: https://frasersgh.com/images/frasers-logo.png

media_folder: 'public/images'
public_folder: '/images'

collections:

# Test Collection
  # - label: 'Menu'
  #   name: 'menuItems'
  #   delete: false
  #   sortable_fields: ['category', 'available', 'itemName']
  #   # view_filters:
  #   #   - label: "Name"
  #   #     field: itemName
  #   #   - label: "Category"
  #   #     field: category
  #   view_groups:
  #     - label: Name
  #       field: itemName
  #     - label: Category
  #       field: category
  #   file: '/public/data/menu-data-test.json'
  #   fields:
  #     - label: 'Menu'
  #       name: 'menu'
  #       widget: 'list'
  #       add_to_top: true
  #       label_singular: 'new menu item'
  #       fields:
  #         - { label: 'Name', name: 'itemName', widget: 'string' }
  #         - {
  #             label: 'Description',
  #             name: 'description',
  #             required: false,
  #             widget: 'text',
  #           }
  #         - {
  #             label: 'Category',
  #             name: 'category',
  #             widget: 'select',
  #             options: ['Starters', 'Entrees', 'Desserts'],
  #           }
  #         - { label: 'Price', name: 'price', widget: 'number' }
  #         - {
  #             label: 'Modifier',
  #             name: 'modifier',
  #             required: false,
  #             hint: 'Add a modifier description',
  #             widget: 'string',
  #           }
  #         - {
  #             label: 'Modifier Price',
  #             name: 'modifierPrice',
  #             required: false,
  #             hint: 'Add the modifier price',
  #             widget: 'number',
  #           }
  #         - {
  #           label: 'Dietary Preferences',
  #           name: 'dietaryPreferences',
  #           required: false,
  #           widget: 'select',
  #           multiple: true,
  #           options: ['Gluten-Free', 'Vegetarian'],
  #         }
  #         - {
  #             label: 'Available',
  #             name: 'available',
  #             hint: 'Select "Available" to show on website',
  #             widget: 'boolean',
  #             default: false,
  #           }

# Main Site Content Collection
  - label: 'Site Content'
    name: 'content'
    delete: false
    sortable_fields: ['category', 'available', 'itemName']
    # view_filters:
    #   - label: "Name"
    #     field: itemName
    #   - label: "Category"
    #     field: category
    view_groups:
      - label: Name
        field: itemName
      - label: Category
        field: category
    files:
  #     - label: 'Site Info'
  #       name: 'business-info'
  #       file: '/public/data/site-data.json'
  #       fields:
  #         - { label: 'Address', name: 'address', widget: 'string' }
  #         - { label: 'Phone Number', name: 'phoneNumber', widget: 'string' }
  #         - { label: 'Announcement 1', name: 'announcement1', widget: 'string' }
  #         - { label: 'Announcement 2', name: 'announcement2', widget: 'string' }
  #         - {
  #             label: 'Announcement 2',
  #             name: 'announcement2',
  #             widget: 'relation',
  #             collection: 'announcements',
  #             value_field: '{{slug}}',
  #             search_field: ['title', 'date'],
  #           }
  #         - {
  #             label: 'Announcement 2',
  #             name: 'announcement2',
  #             widget: 'file',
  #             # media_library: '/posts/',
  #             # allow_multiple: false,
  #           }

      - label: 'Menu'
        name: 'menuData'
        file: '/public/data/menu-data.json'
        fields:
        #   - label: 'Categories'
        #     name: 'Category'
        #     widget: 'object'
        #     fields:
        #       - { label: 'Category', name: 'category', widget: 'list' }
          - label: 'Menu'
            name: 'menu'
            widget: 'list'
            summary: '{{fields.itemName}} - {{fields.price}} - {{fields.category}} - {{fields.available}}'
            add_to_top: true
            label_singular: 'new menu item'
            fields:
              - { label: 'Name', name: 'itemName', widget: 'string' }
              - {
                  label: 'Description',
                  name: 'description',
                  required: false,
                  widget: 'text',
                }
              - {
                  label: 'Category',
                  name: 'category',
                  widget: 'select',
                  options: ['Starters', 'Entrees', 'Desserts'],
                }
              - { label: 'Price', name: 'price', widget: 'number' }
              - {
                  label: 'Modifier',
                  name: 'modifier',
                  required: false,
                  hint: 'Add a modifier description',
                  widget: 'string',
                }
              - {
                  label: 'Modifier Price',
                  name: 'modifierPrice',
                  required: false,
                  hint: 'Add the modifier price',
                  widget: 'number',
                }
              - {
                label: 'Dietary Preferences',
                name: 'dietaryPreferences',
                required: false,
                widget: 'select',
                multiple: true,
                options: ['Gluten-Free', 'Vegetarian'],
              }
              - {
                  label: 'Available',
                  name: 'available',
                  hint: 'Select "Available" to show on website',
                  widget: 'boolean',
                  default: false,
                }

      # - label: 'About Frasers'
      #   name: 'aboutBusiness'
      #   file: '/public/data/about-business.md'
      #   fields:
      #     - {
      #         label: 'Layout',
      #         name: 'layout',
      #         widget: 'hidden',
      #         default: 'about',
      #       }
      #     - { label: 'Title', name: 'title', widget: 'string' }
      #     - {
      #         label: 'Subtitle',
      #         name: 'subtitle',
      #         widget: 'string',
      #         required: false,
      #       }
      #     - { label: 'Publish Date', name: 'date', widget: 'date' }
      #     - { label: 'Image', name: 'imageSource', widget: 'image' }
      #     - {
      #         label: 'Image Alt Text',
      #         name: 'imageAlt',
      #         widget: 'string',
      #         hint: 'Enter alternative text to describe the image to visitors who are unable to see them',
      #       }
      #     - { label: 'Body', name: 'body', widget: 'markdown' }

      # - label: 'About Scott'
      #   name: 'aboutOwner'
      #   file: '/public/data/about-owner.md'
      #   fields:
      #     - {
      #         label: 'Layout',
      #         name: 'layout',
      #         widget: 'hidden',
      #         default: 'about',
      #       }
      #     - { label: 'Title', name: 'title', widget: 'string' }
      #     - {
      #         label: 'Subtitle',
      #         name: 'subtitle',
      #         widget: 'string',
      #         required: false,
      #       }
      #     - { label: 'Publish Date', name: 'date', widget: 'date' }
      #     - { label: 'Image', name: 'imageSource', widget: 'image' }
      #     - {
      #         label: 'Image Alt Text',
      #         name: 'imageAlt',
      #         widget: 'string',
      #         hint: 'Enter alternative text to describe the image to visitors who are unable to see them',
      #       }
      #     - { label: 'Body', name: 'body', widget: 'markdown' }

  # - label: 'Announcements'
  #   name: 'announcements'
  #   label_singular: 'Announcement'
  #   folder: 'posts'
  #   create: true
  #   slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
  #   fields:
  #     - {
  #         label: 'Layout',
  #         name: 'layout',
  #         widget: 'hidden',
  #         default: 'announcement',
  #       }
  #     - { label: 'Title', name: 'title', widget: 'string' }
  #     - {
  #         label: 'Subtitle',
  #         name: 'subtitle',
  #         widget: 'string',
  #         required: false,
  #       }
  #     - { label: 'Publish Date', name: 'date', widget: 'date' }
  #     - { label: 'Image', name: 'imageSource', widget: 'image' }
  #     - {
  #         label: 'Image Alt Text',
  #         name: 'imageAlt',
  #         widget: 'string',
  #         hint: 'Enter alternative text to describe the image to visitors who are unable to see them',
  #       }
  #     - { label: 'Body', name: 'body', widget: 'markdown' }
