backend:
  name: git-gateway
  branch: main

media_folder: 'public/images'
public_folder: '/images'

collections:
  - label: 'Content'
    name: 'content'
    files:
      - label: 'Site Configuration'
        name: 'site-config'
        file: '/public/data/config.json'
        fields:
          - { label: Address, name: address, widget: string }
          - { label: Phone Number, name: phoneNumber, widget: string }
      - label: 'Menu'
        name: 'Menu'
        file: '/public/data/menu.json'
        fields:
          - { label: Menu, name: menu, widget: list }
      - label: 'Double Contents'
        name: 'DoubleContents'
        file: '/public/data/double.json'
        fields:
          - label: 'Double'
            name: ''
            widget: 'list'
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Title, name: title, widget: string }
              - { label: Title, name: title, widget: string }
  - label: 'Menu'
    name: 'menu'
    files:
