backend:
  name: git-gateway
  branch: main

media_folder: 'public/images'
public_folder: '/images'

collections:
  - label: 'Content'
    name: 'content'
    files:
      - label: 'Site Configuration'
        name: 'site-config'
        file: '/public/data/config.json'
        fields:
          - { label: Address, name: address, widget: string }
          - { label: Phone Number, name: phoneNumber, widget: string }
